import { StyleSheet } from 'react-native';
import { COLORS, FONT, SIZES } from '../../../constants';

const styles = StyleSheet.create({
    searchContainer: {
        marginTop: 20,
        alignItems: 'flex-end',
        height: 30,
        //borderStartColor: 'brown',
        width: 300,
        marginLeft: 5,
        backgroundColor: '#06002B00',
        marginBottom: -10,
        marginLeft: 10,

    },
    searchWrapper: {
        flex: 1,
        paddingLeft: 5,
        marginRight: SIZES.large,
        borderRadius: SIZES.xSmall,
        width: '95%',
        backgroundColor: COLORS.white,
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',

    },
    searchInput: {
        fontFamily: FONT.bold,
        color: 'black',
        width: '90%',
        fontSize: SIZES.medium,
        height: '100%',
        paddingHorizontal: 0,
        margin: 0,
    },
    searchInputPlaceholder: {
        fontFamily: FONT.bold,
        color: 'black',
        width: '100%',
        fontSize: SIZES.medium,
        height: '100%',
        paddingHorizontal: 0,
        marginBottom: 10,
    },
    modalSearchContainer: {
        flex: 1,
        paddingTop: 100,
        flexDirection: 'row',
        backgroundColor: '#C7DDFF',
        width: '100%',
        marginLeft: 0,
        marginBottom: -80,
    },
    modalSearchWrapper: {
        flex: 18,
        borderRadius: SIZES.xSmall,
        backgroundColor: 'white',
        marginTop: 20,
        marginLeft: 20,
        marginRight: -9,
        width: '100%',
        height: '30%',
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    modalCloseButton: {
        flex: 2.5,
        marginTop: 20,
        paddingRight: 10,
        paddingLeft: 0,
        //borderWidth: 2,
        marginLeft: 10,
        //backgroundColor: 'white',
        marginRight: 14,
        borderRadius: 40,
        height: '30%',
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalSearchInput: {
        fontFamily: FONT.bold,
        borderWidth: 1,
        borderColor: 'grey',
        color: 'black',
        width: '100%',
        fontSize: SIZES.large,
        backgroundColor: 'white',
        borderRadius: 10,
        height: '100%',
        padding: 10,
        margin: 0,
    },
    flatListContainer: {
        flex: 4,
        backgroundColor: '#C7DDFF',
        paddingLeft: 30,
    },
    searchSuggestion: {
        flex: 1,
        fontWeight: 'bold',
        borderBottomWidth: 20,
        marginBottom: 10,
        marginTop: 10,
        borderBottomColor: 'black',
    }
});

export default styles;
